###
POST http://localhost:3000/user/register HTTP/1.1
Content-Type: application/json
api_key: prueba_api_random

{
"email": "test102@test.com",
"password": "password1"
}
###

PUT http://localhost:3000/user/validation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U1YjFiYmYyOThmZTE2MzEyZWQwYzYiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MzEwNjQ5MSwiZXhwIjoxNzQzMTEzNjkxfQ.mOszc4zOvG4ea9idsLvJqDFMJamUhITjtaDdfjkccDs

{
  "codigo": 618845
}

###
